services:
  api:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    ports:
      - "80:5174"
      - "443:5175"
    env_file:
      - ../.env
    environment:
      PORT: 5174
      REDIS_PORT: 6379
      NODE_ENV: development
    depends_on:
      - db
      - redis
    volumes:
      - ../scripts:/api/scripts
      - ../src:/api/src
  db:
    image: postgres:16
    ports:
      - "5050:5432"
    env_file:
      - ../.env
    environment:
      POSTGRES_DB: api
      POSTGRES_USER: app
    volumes:
      - db_data_dev:/var/lib/postgresql/data_dev
    stop_grace_period: 30s
  redis:
    image: redis:8
    ports:
      - "6379:6379"
    command: ["redis-server", "--appendonly", "yes"]
volumes:
  db_data_dev:
