services:
  api:
    build: .
    ports:
      - "80:5174"
      - "443:5175"
    env_file:
      - .env
    environment:
      DATABASE_URL: ${DATABASE_URL}
      PORT: 5174

      JWT_SECRET: ${JWT_SECRET}

      GOOGLE_AUTH_SECRET: ${GOOGLE_AUTH_SECRET}
      GOOGLE_AUTH_ID: ${GOOGLE_AUTH_ID}

      CALLBACK_URL: ${CALLBACK_URL}

      GITHUB_AUTH_SECRET: ${GITHUB_AUTH_SECRET}
      GITHUB_AUTH_ID: ${GITHUB_AUTH_ID}

      NODE_ENV: ${NODE_ENV}
    depends_on:
      - db
    volumes:
      - ./scripts:/api/scripts
  db:
    image: postgres:16
    ports:
      - "5050:5432"
    environment:
      POSTGRES_DB: api
      POSTGRES_USER: app
      POSTGRES_PASSWORD: ${POSTGRES_PASSWD}
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
