services:
  api:
    build: .
    ports:
      - "80:5174"
      - "443:5175"
    env_file:
      - .env
    environment:
      DATABASE_URL: ${DATABASE_URL}
      PORT: 5174

      JWT_SECRET: ${JWT_SECRET}

      GOOGLE_AUTH_SECRET: ${GOOGLE_AUTH_SECRET}
      GOOGLE_AUTH_ID: ${GOOGLE_AUTH_ID}

      CALLBACK_URL: ${CALLBACK_URL}

      GITHUB_AUTH_SECRET: ${GITHUB_AUTH_SECRET}
      GITHUB_AUTH_ID: ${GITHUB_AUTH_ID}

      REDIS_HOST: ${REDIS_HOST}

      REDIS_PORT: 6379

      NODE_ENV: ${NODE_ENV}
    depends_on:
      - db
      - redis
    volumes:
      - ./scripts:/api/scripts
      - ./src:/api/src
  db:
    image: postgres:16
    ports:
      - "5050:5432"
    environment:
      POSTGRES_DB: api
      POSTGRES_USER: app
      POSTGRES_PASSWORD: ${POSTGRES_PASSWD}
    volumes:
      - db_data:/var/lib/postgresql/data
    stop_grace_period: 30s
  redis:
    image: redis:8
    ports:
      - "6379:6379"
    command: ["redis-server", "--appendonly", "yes"]
volumes:
  db_data:
